// src/App.vue
<template>
    <div class="min-h-screen bg-gray-50 w-full">
        <!-- Header -->
        <header class="bg-white shadow-sm border-b w-full">
            <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
                <h1 class="text-2xl sm:text-3xl font-bold text-gray-900 mb-2">Arxiv AI论文排序</h1>
                <p class="text-gray-600 text-sm sm:text-base">
                    Arxiv当月全部AI学术论文，按引用量排序
                </p>
            </div>
        </header>

        <!-- Control Section -->
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
            <div class="bg-white rounded-lg shadow-sm p-4 sm:p-6 mb-8">
                <!-- Month Selection -->
                <div class="mb-6">
                    <!-- Year and Month Selection in Same Row -->
                    <div class="flex flex-col lg:flex-row gap-4 mb-4">
                        <!-- Year Dropdown -->
                        <div class="lg:w-48">
                            <label class="block text-xs text-gray-500 mb-2">年份</label>
                            <select
                                v-model="selectedYear"
                                @change="onYearChange"
                                class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none text-sm"
                            >
                                <option value="">选择年份</option>
                                <option v-for="year in availableYears" :key="year" :value="year">
                                    {{ year }}年
                                </option>
                            </select>
                        </div>

                        <!-- Month Buttons -->
                        <div v-if="selectedYear" class="flex-1">
                            <label class="block text-xs text-gray-500 mb-2">月份</label>
                            <div
                                class="grid grid-cols-3 sm:grid-cols-4 md:grid-cols-6 lg:grid-cols-12 gap-2"
                            >
                                <button
                                    v-for="month in getAvailableMonthsForYear(selectedYear)"
                                    :key="month"
                                    @click="selectMonthOnly(month)"
                                    :class="[
                                        'px-3 py-2 rounded-lg text-sm font-medium transition-colors',
                                        selectedMonthOnly === month
                                            ? 'bg-blue-600 text-white'
                                            : 'bg-gray-100 text-gray-700 hover:bg-gray-200',
                                    ]"
                                >
                                    {{ month }}月
                                </button>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Keyword Filter -->
                <div>
                    <div class="flex flex-col sm:flex-row gap-4">
                        <input
                            type="text"
                            v-model="filterKeyword"
                            @input="filterPapers"
                            placeholder="输入关键词过滤当月论文..."
                            class="flex-1 px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none text-sm sm:text-base"
                        />
                        <button
                            @click="clearFilter"
                            v-if="filterKeyword"
                            class="px-6 py-3 bg-gray-500 text-white rounded-lg hover:bg-gray-600 transition-colors text-sm sm:text-base whitespace-nowrap"
                        >
                            清除过滤
                        </button>
                    </div>
                </div>
            </div>

            <!-- Results -->
            <div v-if="displayedPapers.length > 0" class="mb-4">
                <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between mb-4">
                    <p class="text-gray-600 mb-2 sm:mb-0">
                        {{ selectedMonthLabel }} 第 {{ currentPage }} 页，共 {{ totalPages }} 页
                        <span v-if="filterKeyword" class="text-blue-600">
                            （过滤后显示 {{ displayedPapers.length }} 篇）
                        </span>
                    </p>
                    <div class="text-sm text-gray-500">按引用量排序</div>
                </div>
            </div>

            <div class="space-y-6">
                <div
                    v-for="(paper, index) in displayedPapers"
                    :key="paper.id"
                    class="bg-white rounded-lg shadow-sm p-4 sm:p-6 hover:shadow-md transition-all duration-200 border border-gray-100 hover:border-blue-200"
                >
                    <!-- Paper ranking and header -->
                    <div class="flex items-start gap-3 sm:gap-4 mb-4">
                        <div
                            class="flex-shrink-0 w-6 h-6 sm:w-8 sm:h-8 bg-blue-100 text-blue-800 rounded-full flex items-center justify-center text-xs sm:text-sm font-semibold"
                        >
                            {{ (currentPage - 1) * pageSize + index + 1 }}
                        </div>
                        <div class="flex-1 min-w-0">
                            <div class="flex items-start gap-4 mb-2">
                                <h2
                                    class="flex-1 text-lg sm:text-xl font-semibold text-gray-900 hover:text-blue-600 cursor-pointer transition-colors min-w-0"
                                    @click="openPaperLink(paper)"
                                >
                                    {{ paper.title }}
                                </h2>
                                <div
                                    class="flex-shrink-0 flex flex-col sm:flex-row items-end sm:items-center gap-2 text-xs sm:text-sm text-gray-500 w-48 sm:w-auto"
                                >
                                    <span
                                        class="bg-red-100 text-red-800 px-2 sm:px-3 py-1 rounded-full font-medium whitespace-nowrap"
                                    >
                                        📊 {{ formatNumber(paper.citations) }}
                                    </span>
                                    <span
                                        class="bg-gray-100 text-gray-700 px-2 sm:px-3 py-1 rounded-full font-mono text-xs whitespace-nowrap"
                                    >
                                        arXiv:{{ paper.arxivId }}
                                    </span>
                                </div>
                            </div>

                            <div
                                class="flex flex-col sm:flex-row sm:items-center gap-1 sm:gap-2 text-sm text-gray-600 mb-3"
                            >
                                <span class="font-medium">作者:</span>
                                <p class="text-gray-700 break-words">
                                    {{ truncateAuthors(paper.authors, 100) }}
                                </p>
                            </div>
                        </div>
                    </div>

                    <!-- Footer with keywords and date -->
                    <div
                        class="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4 pt-4 border-t border-gray-100"
                    >
                        <div class="flex flex-wrap gap-2">
                            <span class="text-sm font-medium text-gray-700 mr-2">关键词:</span>
                            <span
                                v-for="(keyword, keywordIndex) in paper.keywords"
                                :key="keywordIndex"
                                class="px-2 py-1 bg-blue-50 text-blue-700 text-xs rounded-md border border-blue-200 hover:bg-blue-100 cursor-pointer transition-colors"
                                @click="filterByKeyword(keyword)"
                            >
                                #{{ keyword }}
                            </span>
                        </div>
                        <div
                            class="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-4 text-xs text-gray-500"
                        >
                            <span>📅 {{ formatDate(paper.publishedDate) }}</span>
                            <button
                                class="text-blue-600 hover:text-blue-800 font-medium text-left sm:text-center"
                                @click="openPaperLink(paper)"
                            >
                                查看原文 →
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Pagination -->
            <div v-if="totalPages > 1 && !isLoading" class="mt-8 flex justify-center">
                <nav class="flex items-center space-x-2">
                    <!-- First Page -->
                    <button
                        @click="goToFirstPage"
                        :disabled="currentPage === 1"
                        class="px-3 py-2 text-sm font-medium text-gray-500 bg-white border border-gray-300 rounded-md hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                        首页
                    </button>

                    <!-- Previous Page -->
                    <button
                        @click="goToPrevPage"
                        :disabled="currentPage === 1"
                        class="px-3 py-2 text-sm font-medium text-gray-500 bg-white border border-gray-300 rounded-md hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                        上一页
                    </button>

                    <!-- Page Numbers -->
                    <div class="flex items-center space-x-1">
                        <button
                            v-for="page in visiblePages"
                            :key="page"
                            @click="changePage(page)"
                            :class="[
                                'px-3 py-2 text-sm font-medium rounded-md',
                                page === currentPage
                                    ? 'bg-blue-600 text-white'
                                    : 'text-gray-700 bg-white border border-gray-300 hover:bg-gray-50',
                            ]"
                        >
                            {{ page }}
                        </button>
                    </div>

                    <!-- Next Page -->
                    <button
                        @click="goToNextPage"
                        :disabled="currentPage === totalPages"
                        class="px-3 py-2 text-sm font-medium text-gray-500 bg-white border border-gray-300 rounded-md hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                        下一页
                    </button>

                    <!-- Last Page -->
                    <button
                        @click="goToLastPage"
                        :disabled="currentPage === totalPages"
                        class="px-3 py-2 text-sm font-medium text-gray-500 bg-white border border-gray-300 rounded-md hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                        末页
                    </button>
                </nav>
            </div>

            <!-- Page Info -->
            <div v-if="totalPages > 1 && !isLoading" class="mt-4 text-center text-sm text-gray-500">
                第 {{ currentPage }} 页，共 {{ totalPages }} 页
            </div>

            <!-- Error Message -->
            <div
                v-if="loadError && !isLoading"
                class="bg-red-50 border border-red-200 rounded-lg p-4 mb-6"
            >
                <div class="flex items-center">
                    <div class="text-red-800"><strong>加载失败:</strong> {{ loadError }}</div>
                </div>
                <p class="text-red-600 text-sm mt-2">已尝试使用备用数据，如果问题持续请稍后重试</p>
            </div>

            <!-- No results -->
            <div
                v-if="selectedMonth && displayedPapers.length === 0 && !isLoading && !loadError"
                class="text-center py-12"
            >
                <div class="text-gray-400 text-lg mb-2">
                    {{ filterKeyword ? '未找到匹配的论文' : '该月份暂无论文' }}
                </div>
                <p class="text-gray-500">
                    {{ filterKeyword ? '请尝试其他关键词或选择其他月份' : '请选择其他月份' }}
                </p>
            </div>

            <!-- No month selected -->
            <div v-if="!selectedMonth" class="text-center py-12">
                <div class="text-gray-400 text-lg mb-2">请选择月份</div>
                <p class="text-gray-500">选择一个月份来查看该月的推荐论文</p>
            </div>

            <!-- Loading -->
            <div v-if="isLoading" class="text-center py-12">
                <div
                    class="inline-block animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"
                ></div>
                <p class="mt-4 text-gray-600">正在加载论文...</p>
            </div>
        </div>
    </div>
</template>

<script>
export default {
    name: 'App',
    data() {
        return {
            selectedMonth: '',
            selectedYear: '',
            selectedMonthOnly: '',
            filterKeyword: '',
            allMonthlyPapers: [], // 存储该月的全部论文数据
            monthlyPapers: [], // 当前页的论文数据
            displayedPapers: [], // 过滤后显示的数据
            isLoading: false,
            loadError: null,
            currentPage: 1,
            totalPages: 1,
            pageSize: 100,
            startYear: 2020,
            endYear: new Date().getFullYear(),
            endMonth: new Date().getMonth() + 1, // 当前月份
            // 模拟不同月份的论文数据
            papersByMonth: {
                '2020-01': [
                    {
                        id: 101,
                        title: 'Language Models are Unsupervised Multitask Learners',
                        authors:
                            'Alec Radford, Jeffrey Wu, Rewon Child, David Luan, Dario Amodei, Ilya Sutskever',
                        citations: 12543,
                        arxivId: '1909.08593',
                        publishedDate: '2020-01-15',
                        keywords: ['GPT-2', 'language model', 'unsupervised learning', 'NLP'],
                    },
                ],
                '2024-01': [
                    {
                        id: 1,
                        title: 'Attention Is All You Need',
                        authors:
                            'Ashish Vaswani, Noam Shazeer, Niki Parmar, Jakob Uszkoreit, Llion Jones, Aidan N. Gomez, Lukasz Kaiser, Illia Polosukhin',
                        citations: 45672,
                        arxivId: '1706.03762',
                        publishedDate: '2024-01-15',
                        keywords: ['transformer', 'attention', 'neural networks', 'NLP'],
                    },
                    {
                        id: 2,
                        title: 'BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding',
                        authors: 'Jacob Devlin, Ming-Wei Chang, Kenton Lee, Kristina Toutanova',
                        citations: 38291,
                        arxivId: '1810.04805',
                        publishedDate: '2024-01-22',
                        keywords: ['BERT', 'transformer', 'language model', 'pre-training'],
                    },
                ],
            },
        };
    },
    computed: {
        availableYears() {
            const years = [];
            const currentYear = new Date().getFullYear();
            for (let year = 2020; year <= currentYear; year++) {
                years.push(year);
            }
            return years;
        },

        selectedMonthLabel() {
            if (!this.selectedMonth) return '';
            const [year, month] = this.selectedMonth.split('-');
            return `${year}年${parseInt(month)}月`;
        },

        visiblePages() {
            const pages = [];
            const maxVisible = 5; // 最多显示5个页码

            let start = Math.max(1, this.currentPage - Math.floor(maxVisible / 2));
            let end = Math.min(this.totalPages, start + maxVisible - 1);

            // 调整起始位置，确保显示足够的页码
            if (end - start + 1 < maxVisible) {
                start = Math.max(1, end - maxVisible + 1);
            }

            for (let i = start; i <= end; i++) {
                pages.push(i);
            }

            return pages;
        },
    },
    methods: {
        isValidMonth(year, month) {
            // 检查月份是否在有效范围内
            const now = new Date();
            const currentYear = now.getFullYear();
            const currentMonth = now.getMonth() + 1;

            // 不能早于2020年1月
            if (year < 2020 || (year === 2020 && month < 1)) return false;

            // 不能晚于当前年月
            if (year > currentYear || (year === currentYear && month > currentMonth)) return false;

            return true;
        },

        getAvailableMonthsForYear(year) {
            if (!year) return [];

            const now = new Date();
            const currentYear = now.getFullYear();
            const currentMonth = now.getMonth() + 1;

            const months = [];
            const startMonth = year === 2020 ? 1 : 1;
            const endMonth = year === currentYear ? currentMonth : 12;

            for (let month = startMonth; month <= endMonth; month++) {
                months.push(month);
            }

            return months;
        },

        onYearChange() {
            this.selectedMonthOnly = '';
            this.selectedMonth = '';
            this.allMonthlyPapers = [];
            this.monthlyPapers = [];
            this.displayedPapers = [];
            this.currentPage = 1;
            this.totalPages = 1;

            // 默认选择12月（如果12月可用的话）
            if (this.selectedYear) {
                const availableMonths = this.getAvailableMonthsForYear(this.selectedYear);
                if (availableMonths.includes(12)) {
                    this.selectMonthOnly(12);
                } else if (availableMonths.length > 0) {
                    // 如果12月不可用，选择该年份的最后一个可用月份
                    this.selectMonthOnly(availableMonths[availableMonths.length - 1]);
                }
            }
        },

        selectMonthOnly(month) {
            this.selectedMonthOnly = month;
            if (this.selectedYear && month) {
                const monthValue = `${this.selectedYear}-${month.toString().padStart(2, '0')}`;
                this.selectMonth(monthValue);
            }
        },

        selectMonth(monthValue) {
            this.selectedMonth = monthValue;
            const [year, month] = monthValue.split('-');
            this.selectedYear = parseInt(year);
            this.selectedMonthOnly = parseInt(month);
            this.filterKeyword = '';
            this.currentPage = 1;
            this.totalPages = 1;
            this.loadMonthlyPapers();
        },

        async loadMonthlyPapers() {
            this.isLoading = true;
            this.loadError = null;

            try {
                // 将 YYYY-MM 格式转换为 YYYYMM 格式
                const monthParam = this.selectedMonth.replace('-', '');

                // 一次性加载该月的全部数据
                await this.loadAllMonthData(monthParam);

                // 计算总页数
                this.calculateTotalPages();

                // 更新当前页显示的数据
                this.updateCurrentPageData();
            } catch (error) {
                console.error('获取论文数据失败:', error);
                this.loadError = error.message;

                // 如果API请求失败，使用本地模拟数据作为备用
                const fallbackData = this.papersByMonth[this.selectedMonth] || [];
                if (fallbackData.length > 0) {
                    this.allMonthlyPapers = fallbackData.sort((a, b) => b.citations - a.citations);
                    this.calculateTotalPages();
                    this.updateCurrentPageData();
                    this.loadError = null; // 清除错误，因为有备用数据
                } else {
                    this.allMonthlyPapers = [];
                    this.monthlyPapers = [];
                    this.displayedPapers = [];
                    this.totalPages = 1;
                    this.currentPage = 1;
                }
            }

            this.isLoading = false;
        },

        async loadAllMonthData(monthParam) {
            const response = await fetch(`http://125.34.17.225:9300/meta/${monthParam}`);

            if (!response.ok) {
                throw new Error(`HTTP error! status: ${response.status}`);
            }

            const result = await response.json();

            if (result.ret === 'ok' && result.data) {
                // 转换API数据格式为组件需要的格式，后端已按引用量排序，直接使用后端返回的id
                this.allMonthlyPapers = result.data.map((paper) => ({
                    id: paper.id,
                    title: paper.title,
                    authors: paper.authors,
                    citations: paper.citations,
                    arxivId: this.extractArxivId(paper.url),
                    publishedDate: this.formatPublishedDate(paper.publishedMonth),
                    keywords: paper.keywords || [],
                    url: paper.url,
                }));
            } else {
                throw new Error('API返回数据格式错误');
            }
        },

        calculateTotalPages() {
            this.totalPages = Math.max(1, Math.ceil(this.allMonthlyPapers.length / this.pageSize));
        },

        updateCurrentPageData() {
            const startIndex = (this.currentPage - 1) * this.pageSize;
            const endIndex = startIndex + this.pageSize;

            // 从全部数据中截取当前页的数据，直接使用后端返回的id
            this.monthlyPapers = this.allMonthlyPapers.slice(startIndex, endIndex);

            // 应用关键词过滤
            this.filterPapers();
        },

        filterPapers() {
            if (!this.filterKeyword.trim()) {
                this.displayedPapers = [...this.monthlyPapers];
                return;
            }

            const keyword = this.filterKeyword.toLowerCase();
            this.displayedPapers = this.monthlyPapers.filter(
                (paper) =>
                    paper.title.toLowerCase().includes(keyword) ||
                    paper.authors.toLowerCase().includes(keyword) ||
                    paper.keywords.some((k) => k.toLowerCase().includes(keyword)),
            );
        },

        filterByKeyword(keyword) {
            this.filterKeyword = keyword;
            this.filterPapers();
        },

        clearFilter() {
            this.filterKeyword = '';
            this.displayedPapers = [...this.monthlyPapers];
        },

        changePage(page) {
            if (page < 1 || page > this.totalPages || page === this.currentPage) {
                return;
            }

            this.currentPage = page;

            // 前端分页，无需API请求
            this.updateCurrentPageData();
        },

        goToFirstPage() {
            this.changePage(1);
        },

        goToLastPage() {
            this.changePage(this.totalPages);
        },

        goToPrevPage() {
            this.changePage(this.currentPage - 1);
        },

        goToNextPage() {
            this.changePage(this.currentPage + 1);
        },

        openArxivLink(arxivId) {
            window.open(`https://arxiv.org/abs/${arxivId}`, '_blank');
        },

        formatNumber(num) {
            return num.toLocaleString();
        },

        extractArxivId(url) {
            // 从URL中提取arXiv ID
            // 例如: https://arxiv.org/pdf/2506.01939 -> 2506.01939
            const match = url.match(/arxiv\.org\/pdf\/([^\/]+)/);
            return match ? match[1] : '';
        },

        formatPublishedDate(publishedMonth) {
            // 将 YYYYMM 格式转换为 YYYY-MM-01 格式
            if (publishedMonth && publishedMonth.length === 6) {
                const year = publishedMonth.substring(0, 4);
                const month = publishedMonth.substring(4, 6);
                return `${year}-${month}-01`;
            }
            return '';
        },

        openPaperLink(paper) {
            // 优先使用paper.url，如果没有则使用arxivId构建链接
            if (paper.url) {
                window.open(paper.url, '_blank');
            } else if (paper.arxivId) {
                window.open(`https://arxiv.org/abs/${paper.arxivId}`, '_blank');
            }
        },

        truncateAuthors(authors, maxLength) {
            if (!authors || authors.length <= maxLength) {
                return authors;
            }
            return authors.substring(0, maxLength) + '...';
        },

        formatDate(dateString) {
            return new Date(dateString).toLocaleDateString('zh-CN');
        },
    },

    mounted() {
        // 默认选择当前月份或最新可用月份
        const now = new Date();
        const currentYear = now.getFullYear();
        const currentMonth = now.getMonth() + 1;

        if (this.isValidMonth(currentYear, currentMonth)) {
            const monthValue = `${currentYear}-${currentMonth.toString().padStart(2, '0')}`;
            this.selectMonth(monthValue);
        } else {
            // 选择最新的可用月份（当前年月）
            const monthValue = `${currentYear}-${currentMonth.toString().padStart(2, '0')}`;
            this.selectMonth(monthValue);
        }
    },
};
</script>

// app/page.tsx
'use client';

import { useState } from 'react';

export default function Page() {
    const [searchQuery, setSearchQuery] = useState('');
    const [searchResults, setSearchResults] = useState([]);
    const [isLoading, setIsLoading] = useState(false);

    // Mock search results data
    const mockResults = [
        {
            id: 1,
            title: 'Attention Is All You Need',
            authors:
                'Ashish Vaswani, Noam Shazeer, Niki Parmar, Jakob Uszkoreit, Llion Jones, Aidan N. Gomez, Lukasz Kaiser, Illia Polosukhin',
            abstract:
                'The dominant sequence transduction models are based on complex recurrent or convolutional neural networks...',
            citations: 45672,
            arxivId: '1706.03762',
            publishedDate: '2017-06-12',
            keywords: ['transformer', 'attention', 'neural networks', 'NLP'],
        },
        {
            id: 2,
            title: 'BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding',
            authors: 'Jacob Devlin, Ming-Wei Chang, Kenton Lee, Kristina Toutanova',
            abstract:
                'We introduce a new language representation model called BERT, which stands for Bidirectional Encoder Representations from Transformers...',
            citations: 38291,
            arxivId: '1810.04805',
            publishedDate: '2018-10-11',
            keywords: ['BERT', 'transformer', 'language model', 'pre-training'],
        },
        {
            id: 3,
            title: 'Deep Residual Learning for Image Recognition',
            authors: 'Kaiming He, Xiangyu Zhang, Shaoqing Ren, Jian Sun',
            abstract:
                'Deeper neural networks are more difficult to train. We present a residual learning framework to ease the training...',
            citations: 89234,
            arxivId: '1512.03385',
            publishedDate: '2015-12-10',
            keywords: ['ResNet', 'deep learning', 'computer vision', 'residual networks'],
        },
        {
            id: 4,
            title: 'Generative Adversarial Networks',
            authors:
                'Ian J. Goodfellow, Jean Pouget-Abadie, Mehdi Mirza, Bing Xu, David Warde-Farley, Sherjil Ozair, Aaron Courville, Yoshua Bengio',
            abstract:
                'We propose a new framework for estimating generative models via an adversarial process...',
            citations: 67543,
            arxivId: '1406.2661',
            publishedDate: '2014-06-10',
            keywords: ['GAN', 'generative models', 'adversarial training', 'deep learning'],
        },
    ];

    const handleSearch = () => {
        if (!searchQuery.trim()) return;

        setIsLoading(true);

        // Simulate API call
        setTimeout(() => {
            // Filter and sort by citations (descending)
            const filtered = mockResults
                .filter(
                    (paper) =>
                        paper.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
                        paper.keywords.some((keyword) =>
                            keyword.toLowerCase().includes(searchQuery.toLowerCase()),
                        ) ||
                        paper.abstract.toLowerCase().includes(searchQuery.toLowerCase()),
                )
                .sort((a, b) => b.citations - a.citations);

            setSearchResults(filtered);
            setIsLoading(false);
        }, 1000);
    };

    const handleKeyPress = (e) => {
        if (e.key === 'Enter') {
            handleSearch();
        }
    };

    return (
        <div className="min-h-screen bg-gray-50 w-[1443px] h-[1025px]" data-oid="xmh7k6g">
            {/* Header */}
            <header className="bg-white shadow-sm border-b" data-oid="02t1xgc">
                <div className="max-w-6xl mx-auto px-4 py-6" data-oid="2w4c3v4">
                    <h1 className="text-3xl font-bold text-gray-900 mb-2" data-oid="ufg8y-_">
                        ArXiv 论文搜索
                    </h1>
                    <p className="text-gray-600" data-oid=":_w4bwx">
                        按引用量排序的学术论文关键词搜索
                    </p>
                </div>
            </header>

            {/* Search Section */}
            <div className="max-w-6xl mx-auto px-4 py-8" data-oid="pdvnyz.">
                <div className="bg-white rounded-lg shadow-sm p-6 mb-8" data-oid="daso_2q">
                    <div className="flex gap-4" data-oid="aunyibx">
                        <input
                            type="text"
                            value={searchQuery}
                            onChange={(e) => setSearchQuery(e.target.value)}
                            onKeyPress={handleKeyPress}
                            placeholder="输入关键词搜索论文..."
                            className="flex-1 px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
                            data-oid="bh.nsek"
                        />

                        <button
                            onClick={handleSearch}
                            disabled={isLoading}
                            className="px-8 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                            data-oid="c6mklyz"
                        >
                            {isLoading ? '搜索中...' : '搜索'}
                        </button>
                    </div>
                </div>

                {/* Results */}
                {searchResults.length > 0 && (
                    <div className="mb-4" data-oid="60hskwd">
                        <p className="text-gray-600" data-oid="rmpj.jr">
                            找到 {searchResults.length} 篇论文，按引用量排序
                        </p>
                    </div>
                )}

                <div className="space-y-6" data-oid="ai7x9l5">
                    {searchResults.map((paper, index) => (
                        <div
                            key={paper.id}
                            className="bg-white rounded-lg shadow-sm p-6 hover:shadow-md transition-all duration-200 border border-gray-100 hover:border-blue-200"
                            data-oid="1s4ktbq"
                        >
                            {/* Paper ranking and header */}
                            <div className="flex items-start gap-4 mb-4" data-oid="br07q6f">
                                <div
                                    className="flex-shrink-0 w-8 h-8 bg-blue-100 text-blue-800 rounded-full flex items-center justify-center text-sm font-semibold"
                                    data-oid="q-5mx.0"
                                >
                                    {index + 1}
                                </div>
                                <div className="flex-1" data-oid="o.swj6p">
                                    <div
                                        className="flex justify-between items-start mb-2"
                                        data-oid="moyadkx"
                                    >
                                        <h2
                                            className="text-xl font-semibold text-gray-900 hover:text-blue-600 cursor-pointer transition-colors"
                                            data-oid="r-a3beo"
                                            onClick={() =>
                                                window.open(
                                                    `https://arxiv.org/abs/${paper.arxivId}`,
                                                    '_blank',
                                                )
                                            }
                                        >
                                            {paper.title}
                                        </h2>
                                        <div
                                            className="flex items-center gap-3 text-sm text-gray-500 ml-4"
                                            data-oid="bukciea"
                                        >
                                            <span
                                                className="bg-red-100 text-red-800 px-3 py-1 rounded-full font-medium"
                                                data-oid="8ga0h2e"
                                            >
                                                📊 {paper.citations.toLocaleString()}
                                            </span>
                                            <span
                                                className="bg-gray-100 text-gray-700 px-3 py-1 rounded-full font-mono text-xs"
                                                data-oid="_at780g"
                                            >
                                                arXiv:{paper.arxivId}
                                            </span>
                                        </div>
                                    </div>

                                    <div
                                        className="flex items-center gap-2 text-sm text-gray-600 mb-3"
                                        data-oid="wtkigjo"
                                    >
                                        <span className="font-medium" data-oid="q_ffur1">
                                            作者:
                                        </span>
                                        <p className="text-gray-700" data-oid="0o-kc8s">
                                            {paper.authors}
                                        </p>
                                    </div>
                                </div>
                            </div>

                            {/* Abstract */}
                            <div className="mb-4" data-oid="tuu2qwh">
                                <h3
                                    className="text-sm font-medium text-gray-800 mb-2"
                                    data-oid="ob:9u8u"
                                >
                                    摘要
                                </h3>
                                <p
                                    className="text-gray-600 leading-relaxed text-sm"
                                    data-oid=".40rzf3"
                                >
                                    {paper.abstract.length > 300
                                        ? `${paper.abstract.substring(0, 300)}...`
                                        : paper.abstract}
                                </p>
                            </div>

                            {/* Footer with keywords and date */}
                            <div
                                className="flex items-center justify-between pt-4 border-t border-gray-100"
                                data-oid="vpgoq_h"
                            >
                                <div className="flex flex-wrap gap-2" data-oid="rzi5b19">
                                    <span
                                        className="text-sm font-medium text-gray-700 mr-2"
                                        data-oid="..-da3x"
                                    >
                                        关键词:
                                    </span>
                                    {paper.keywords.map((keyword, keywordIndex) => (
                                        <span
                                            key={keywordIndex}
                                            className="px-2 py-1 bg-blue-50 text-blue-700 text-xs rounded-md border border-blue-200 hover:bg-blue-100 cursor-pointer transition-colors"
                                            data-oid="yl-ij-z"
                                            onClick={() => setSearchQuery(keyword)}
                                        >
                                            #{keyword}
                                        </span>
                                    ))}
                                </div>
                                <div
                                    className="flex items-center gap-4 text-xs text-gray-500"
                                    data-oid="y1tn13c"
                                >
                                    <span data-oid="ysqbmx1">
                                        📅{' '}
                                        {new Date(paper.publishedDate).toLocaleDateString('zh-CN')}
                                    </span>
                                    <button
                                        className="text-blue-600 hover:text-blue-800 font-medium"
                                        onClick={() =>
                                            window.open(
                                                `https://arxiv.org/abs/${paper.arxivId}`,
                                                '_blank',
                                            )
                                        }
                                        data-oid="el85325"
                                    >
                                        查看原文 →
                                    </button>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>

                {/* No results */}
                {searchQuery && searchResults.length === 0 && !isLoading && (
                    <div className="text-center py-12" data-oid="9cf4nfj">
                        <div className="text-gray-400 text-lg mb-2" data-oid="8w7bh8v">
                            未找到相关论文
                        </div>
                        <p className="text-gray-500" data-oid="2y02t84">
                            请尝试其他关键词
                        </p>
                    </div>
                )}

                {/* Loading */}
                {isLoading && (
                    <div className="text-center py-12" data-oid="z-p-:bi">
                        <div
                            className="inline-block animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"
                            data-oid="may9xpl"
                        ></div>
                        <p className="mt-4 text-gray-600" data-oid="lr6zl6k">
                            正在搜索论文...
                        </p>
                    </div>
                )}
            </div>
        </div>
    );
}
